// Generated by keyloom routes command
import type { KeyloomRoutesManifest } from '@keyloom/nextjs/route-types'

const manifest: KeyloomRoutesManifest = {
  "generatedAt": "2025-10-01T14:19:49.930Z",
  "entries": []
}

export default manifest
export const routes = manifest.entries
